// Testing helper: randomize every storefront item's price to one of the small
// naira tiers below, then rewrite assets/photoshoot.js + assets/newDrop.js.
// Run the seed scripts afterwards to sync the DB (product pages read the DB).
//
//   node scripts/randomizePrices.mjs
//
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

// sale price -> struck "was" price (kept small — we're still testing).
// Real intent: 45k (from 48k), 38k (from 40k), 35k (from 38k).
const TIERS = [
  { offerPrice: 45, price: 48 },
  { offerPrice: 38, price: 40 },
  { offerPrice: 35, price: 38 },
];
const pick = () => TIERS[Math.floor(Math.random() * TIERS.length)];

const photoURL = new URL('../assets/photoshoot.js', import.meta.url);
const newDropURL = new URL('../assets/newDrop.js', import.meta.url);

const photo = await import(photoURL);
photo.trending.forEach((p) => Object.assign(p, pick()));
fs.writeFileSync(fileURLToPath(photoURL),
`// AUTO-GENERATED by scripts/uploadPhotoshoot.mjs — do not edit by hand.
export const trending = ${JSON.stringify(photo.trending, null, 2)};

export const photoBanners = ${JSON.stringify(photo.photoBanners, null, 2)};

export const featuredCategories = ${JSON.stringify(photo.featuredCategories, null, 2)};
`);

const nd = await import(newDropURL);
nd.newDrop.forEach((p) => Object.assign(p, pick()));
fs.writeFileSync(fileURLToPath(newDropURL),
`// AUTO-GENERATED by scripts/uploadNewDrop.mjs — edit the images/manifest, not this file.
export const newDropMeta = ${JSON.stringify(nd.newDropMeta, null, 2)};

export const newDrop = ${JSON.stringify(nd.newDrop, null, 2)};
`);

console.log(`✓ Randomized prices — ${photo.trending.length} trending + ${nd.newDrop.length} new-drop items (tiers: ₦45/₦38/₦35).`);
