// Set real retail prices on every storefront item using three flat naira tiers,
// assigned by product type. Sets price === offerPrice (no fake discount), then
// rewrites assets/photoshoot.js + assets/newDrop.js. Run the seed scripts after
// to sync the DB (product pages / cart / the actual Paystack charge read the DB).
//
//   node scripts/setRealPrices.mjs
//
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

// ₦ tiers by product type. offerPrice = sale (what they pay), price = higher
// "was" so the red strikethrough discount shows.
const TIERS = {
  premium: { offerPrice: 45000, price: 55000 }, // quarter-zips, long-sleeve compression, joggers, hoodie, women's 2-piece sets, jumpsuit
  mid:     { offerPrice: 38000, price: 45000 }, // shorts, jorts, short-sleeve compression tee, bodysuit
  basic:   { offerPrice: 35000, price: 42000 }, // tees, tanks
};

function tierFor(p) {
  const t = `${p.slug || ''} ${p.name || ''} ${p.tag || ''}`.toLowerCase();
  if (/quarter-?zip|long-?sleeve|longsleeve|jogger|hoodie|jumpsuit|(^|[^a-z])set([^a-z]|$)|two-piece|seamless/.test(t)) return TIERS.premium;
  if (/shorts|jorts|bodysuit|compression[ -]tee/.test(t)) return TIERS.mid;
  return TIERS.basic; // tees, tanks, default
}

function priceAll(list) {
  return list.map((p) => {
    const t = tierFor(p);
    return `${p.name}${p.tag ? ' - ' + p.tag : ''} -> ₦${t.offerPrice.toLocaleString()} (was ₦${t.price.toLocaleString()})`;
  });
}

const photoURL = new URL('../assets/photoshoot.js', import.meta.url);
const newDropURL = new URL('../assets/newDrop.js', import.meta.url);

const photo = await import(photoURL);
photo.trending.forEach((p) => { Object.assign(p, tierFor(p)); });
fs.writeFileSync(fileURLToPath(photoURL),
`// AUTO-GENERATED by scripts/uploadPhotoshoot.mjs — do not edit by hand.
export const trending = ${JSON.stringify(photo.trending, null, 2)};

export const photoBanners = ${JSON.stringify(photo.photoBanners, null, 2)};

export const featuredCategories = ${JSON.stringify(photo.featuredCategories, null, 2)};
`);

const nd = await import(newDropURL);
nd.newDrop.forEach((p) => { Object.assign(p, tierFor(p)); });
fs.writeFileSync(fileURLToPath(newDropURL),
`// AUTO-GENERATED by scripts/uploadNewDrop.mjs — edit the images/manifest, not this file.
export const newDropMeta = ${JSON.stringify(nd.newDropMeta, null, 2)};

export const newDrop = ${JSON.stringify(nd.newDrop, null, 2)};
`);

console.log('✓ Set real prices (₦45,000 / ₦38,000 / ₦35,000 by type):\n');
console.log([...priceAll(photo.trending), ...priceAll(nd.newDrop)].map((l) => '  ' + l).join('\n'));
