// One-off: swap two angle URLs within specific New Drop colorways (fix front/back
// or front/side orientation) without re-uploading. Edits assets/newDrop.js in place.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'assets', 'newDrop.js');

// [slug, colorway name, angleA, angleB] — swaps the two URLs
const SWAPS = [
  ['leopard-set', 'Burgundy', 'front', 'back'],
  ['compression-longsleeve', 'White', 'front', 'back'],
  ['compression-longsleeve', 'Black', 'front', 'side'],
  ['shredded-ls-set', 'Black', 'front', 'back'],
  ['contrast-shorts', 'Black', 'front', 'back'],
  ['piped-set', 'Red', 'front', 'back'],
];

const txt = fs.readFileSync(OUT, 'utf8');
const meta = JSON.parse(txt.split('export const newDropMeta =')[1].split('export const newDrop =')[0].trim().replace(/;\s*$/, ''));
const arr = JSON.parse(txt.split('export const newDrop =')[1].trim().replace(/;\s*$/, ''));

for (const [slug, cwName, a, b] of SWAPS) {
  const p = arr.find((x) => x.slug === slug);
  const cw = p?.colorways.find((c) => c.name === cwName);
  if (!cw) { console.warn(`⚠ not found: ${slug}/${cwName}`); continue; }
  if (!cw.angles[a] || !cw.angles[b]) { console.warn(`⚠ ${slug}/${cwName} missing ${a} or ${b}`); continue; }
  [cw.angles[a], cw.angles[b]] = [cw.angles[b], cw.angles[a]];
  console.log(`swapped ${a}<->${b}: ${p.name} - ${cwName}`);
}

const banner = '// AUTO-GENERATED by scripts/uploadNewProducts.mjs — edit the images, not this file.';
fs.writeFileSync(OUT, `${banner}\nexport const newDropMeta = ${JSON.stringify(meta, null, 2)};\n\nexport const newDrop = ${JSON.stringify(arr, null, 2)};\n`);
console.log('✓ newDrop.js updated');
